[package]
name = "pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
console = "0.15.8"
indicatif = "0.17.8"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"
